# backend/data/churches.py

CHURCHES = [
    {
        "id": "etchmiadzin",
        "name_hy": "Էջմիածնի Մայր Տաճար",
        "name_en": "Etchmiadzin Mother Cathedral",
        "period": "old",
        "century": "IV դար",
        "year": 301,
        "location_hy": "Վաղարշապատ (Էջմիածին), Արմավիրի մարզ",
        "location_en": "Vagharshapat (Etchmiadzin), Armavir Province",
        "address_hy": "Արարատյան 1, Վաղարշապատ 1101",
        "address_en": "Araratyan 1, Vagharshapat 1101",
        "unesco": True,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=40.1596,44.2919",
        "image_main": "/static/img/churches/etchmiadzin-old-1.jpg",
        "image_old": "/static/img/churches/etchmiadzin-old-1.jpg",
        "image_new": "/static/img/churches/etchmiadzin-old-2.jpg",
        "images": [
            "/static/img/churches/etchmiadzin-old-1.jpg",
            "/static/img/churches/etchmiadzin-old-2.jpg",
        ],
    },
    {
        "id": "artashat-octagon",
        "name_hy": "Արտաշատի ութանկյուն եկեղեցի",
        "name_en": "Artashat Octagonal Church",
        "period": "old",
        "century": "IV դար",
        "year": 330,
        "location_hy": "Հին Արտաշատ (Արտաքսատ), Արարատի մարզ",
        "location_en": "Ancient Artashat (Artaxata), Ararat Province",
        "address_hy": "Հին Արտաշատ, Արարատի մարզ",
        "address_en": "Ancient Artashat, Ararat Province",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=39.9010,44.5720",
        "image_main": "/static/img/churches/artashat-octagon-1.jpg",
        "image_old": "/static/img/churches/artashat-octagon-1.jpg",
        "image_new": "/static/img/churches/artashat-octagon-2.jpg",
        "images": [
            "/static/img/churches/artashat-octagon-1.jpg",
            "/static/img/churches/artashat-octagon-2.jpg",
        ],
    },
    {
        "id": "hripsime",
        "name_hy": "Սուրբ Հռիփսիմե եկեղեցի",
        "name_en": "Saint Hripsime Church",
        "period": "old",
        "century": "VII դար",
        "year": 618,
        "location_hy": "Վաղարշապատ (Էջմիածին), Արմավիրի մարզ",
        "location_en": "Vagharshapat (Etchmiadzin), Armavir Province",
        "address_hy": "Հռիփսիմե 85, Վաղարշապատ",
        "address_en": "Hripsime 85, Vagharshapat",
        "unesco": True,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=40.1611,44.2919",
        "image_main": "/static/img/churches/hripsime-old.jpg",
        "image_old": "/static/img/churches/hripsime-old.jpg",
        "image_new": "/static/img/churches/hripsime-new.jpg",
        "images": [
            "/static/img/churches/hripsime-old.jpg",
            "/static/img/churches/hripsime-new.jpg",
        ],
    },
    {
        "id": "gayane",
        "name_hy": "Սուրբ Գայանե եկեղեցի",
        "name_en": "Saint Gayane Church",
        "period": "old",
        "century": "VII դար",
        "year": 630,
        "location_hy": "Վաղարշապատ (Էջմիածին), Արմավիրի մարզ",
        "location_en": "Vagharshapat (Etchmiadzin), Armavir Province",
        "address_hy": "Վաղարշապատ, Արմավիրի մարզ",
        "address_en": "Vagharshapat, Armavir Province",
        "unesco": True,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=40.1578,44.2911",
        "image_main": "/static/img/churches/gayane-old.jpg",
        "image_old": "/static/img/churches/gayane-old.jpg",
        "image_new": "/static/img/churches/gayane-new.jpg",
        "images": [
            "/static/img/churches/gayane-old.jpg",
            "/static/img/churches/gayane-new.jpg",
        ],
    },
    {
        "id": "khor-virap",
        "name_hy": "Խոր Վիրապ վանք",
        "name_en": "Khor Virap Monastery",
        "period": "old",
        "century": "XVII դար (ներկայիս)",
        "year": 642,
        "location_hy": "Արարատի մարզ, Արտաշատին մոտ",
        "location_en": "Ararat Province, near Artashat",
        "address_hy": "Արարատի մարզ, Խոր Վիրապ",
        "address_en": "Khor Virap, Ararat Province",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=39.8284,44.5619",
        "image_main": "/static/img/churches/khor-virap-new.jpg",
        "image_old": "/static/img/churches/khor-virap-old.jpg",
        "image_new": "/static/img/churches/khor-virap-new.jpg",
        "images": [
            "/static/img/churches/khor-virap-old.jpg",
            "/static/img/churches/khor-virap-new.jpg",
        ],
    },
    {
        "id": "sevanavank",
        "name_hy": "Սևանավանք",
        "name_en": "Sevanavank Monastery",
        "period": "old",
        "century": "IX դար",
        "year": 874,
        "location_hy": "Սևան, Գեղարքունիքի մարզ",
        "location_en": "Sevan, Gegharkunik Province",
        "address_hy": "Սևան, Գեղարքունիքի մարզ",
        "address_en": "Sevan, Gegharkunik Province",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=40.5614,44.9494",
        "image_main": "/static/img/churches/sevanavank.jpg",
        "image_old": "/static/img/churches/sevanavank_old.png",
        "image_new": "/static/img/churches/sevanavank_new.jpg",
        "images": [
            "/static/img/churches/sevanavank_old.png",
            "/static/img/churches/sevanavank.jpg",
            "/static/img/churches/sevanavank_new.jpg",
        ],
    },
    {
        "id": "geghard",
        "name_hy": "Գեղարդի վանք",
        "name_en": "Geghard Monastery",
        "period": "old",
        "century": "XIII դար",
        "year": 1215,
        "location_hy": "Կոտայքի մարզ, Ազատ գետի կիրճ",
        "location_en": "Kotayk Province, Azat River gorge",
        "address_hy": "Կոտայքի մարզ, Գեղարդավանք",
        "address_en": "Geghard Monastery, Kotayk Province",
        "unesco": True,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=40.1415,44.8143",
        "image_main": "/static/img/churches/geghard-outside-main.jpg",
        "image_old": "/static/img/churches/geghard-khachkars.jpg",
        "image_new": "/static/img/churches/geghard-outside-main.jpg",
        "images": [
            "/static/img/churches/geghard-khachkars.jpg",
            "/static/img/churches/geghard-outside-main.jpg",
            "/static/img/churches/Geghard-qarer.jpg",
        ],
    },
    {
        "id": "noravank",
        "name_hy": "Նորավանք",
        "name_en": "Noravank Monastery",
        "period": "old",
        "century": "XIII դար",
        "year": 1205,
        "location_hy": "Վայոց ձոր, Ամաղու գյուղի մոտ",
        "location_en": "Vayots Dzor, near Amaghu village",
        "address_hy": "Վայոց ձոր, Նորավանք",
        "address_en": "Noravank, Vayots Dzor",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=39.6836,45.2311",
        "image_main": "/static/img/churches/noravank-new.jpg",
        "image_old": "/static/img/churches/noravank-old.jpg",
        "image_new": "/static/img/churches/noravank-new.jpg",
        "images": [
            "/static/img/churches/noravank-old.jpg",
            "/static/img/churches/noravank-new.jpg",
            "/static/img/churches/noravank-min.webp",
        ],
    },
    {
        "id": "tatev",
        "name_hy": "Տաթևի վանք",
        "name_en": "Tatev Monastery",
        "period": "old",
        "century": "IX–X դար",
        "year": 910,
        "location_hy": "Սյունիքի մարզ, Տաթև գյուղ",
        "location_en": "Syunik Province, Tatev village",
        "address_hy": "Տաթև 3218, Սյունիքի մարզ",
        "address_en": "Tatev 3218, Syunik Province",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=39.3797,46.2442",
        "image_main": "/static/img/churches/tatev.jpg",
        "image_old": "/static/img/churches/tatev-old.jpg",
        "image_new": "/static/img/churches/tatev.jpg",
        "images": [
            "/static/img/churches/tatev-old.jpg",
            "/static/img/churches/tatev.jpg",
            "/static/img/churches/tatev-door.avif",
        ],
    },
    {
        "id": "haghpat",
        "name_hy": "Հաղպատի վանք",
        "name_en": "Haghpat Monastery",
        "period": "old",
        "century": "X դար",
        "year": 976,
        "location_hy": "Լոռու մարզ, Հաղպատ գյուղ",
        "location_en": "Lori Province, Haghpat village",
        "address_hy": "Հաղպատ, Լոռու մարզ",
        "address_en": "Haghpat, Lori Province",
        "unesco": True,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=41.0965,44.7048",
        "image_main": "/static/img/churches/haghpat.jpg",
        "image_old": "/static/img/churches/haghpat-old.jpg",
        "image_new": "/static/img/churches/haghpat-new.jpg",
        "images": [
            "/static/img/churches/haghpat-old.jpg",
            "/static/img/churches/haghpat-new.jpg",
            "/static/img/churches/haghpat.jpg",
        ],
    },
    {
        "id": "sanahin",
        "name_hy": "Սանահինի վանք",
        "name_en": "Sanahin Monastery",
        "period": "old",
        "century": "X դար",
        "year": 966,
        "location_hy": "Լոռու մարզ, Սանահին գյուղ",
        "location_en": "Lori Province, Sanahin village",
        "address_hy": "Սանահին 1705, Լոռու մարզ",
        "address_en": "Sanahin 1705, Lori Province",
        "unesco": True,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=41.1009,44.6997",
        "image_main": "/static/img/churches/sanahin-new.jpg",
        "image_old": "/static/img/churches/sanahin-old.jpg",
        "image_new": "/static/img/churches/sanahin-new.jpg",
        "images": [
            "/static/img/churches/sanahin-old.jpg",
            "/static/img/churches/sanahin-new.jpg",
        ],
    },
    {
        "id": "haghartsin",
        "name_hy": "Հաղարծինի վանք",
        "name_en": "Haghartsin Monastery",
        "period": "old",
        "century": "XII–XIII դար",
        "year": 1200,
        "location_hy": "Տավուշի մարզ, Դիլիջան",
        "location_en": "Tavush Province, Dilijan",
        "address_hy": "Հաղարծին 3902, Տավուշի մարզ",
        "address_en": "Haghartsin 3902, Tavush Province",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=40.8012,44.9623",
        "image_main": "/static/img/churches/haghartin.jpg",
        "image_old": "/static/img/churches/aghartin.jpg",
        "image_new": "/static/img/churches/haghartin.jpg",
        "images": [
            "/static/img/churches/aghartin.jpg",
            "/static/img/churches/haghartin.jpg",
            "/static/img/churches/agarcin4.jpeg",
        ],
    },
    {
        "id": "goshavank",
        "name_hy": "Գոշավանք",
        "name_en": "Goshavank Monastery",
        "period": "old",
        "century": "XII–XIII դար",
        "year": 1191,
        "location_hy": "Տավուշի մարզ, Գոշ գյուղ",
        "location_en": "Tavush Province, Gosh village",
        "address_hy": "Գոշ 3907, Տավուշի մարզ",
        "address_en": "Gosh 3907, Tavush Province",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=40.8178,44.8756",
        "image_main": "/static/img/churches/goshavank.jpg",
        "image_old": "/static/img/churches/goshavank-old.jpg",
        "image_new": "/static/img/churches/goshavank-new.webp",
        "images": [
            "/static/img/churches/goshavank-old.jpg",
            "/static/img/churches/goshavank-new.webp",
            "/static/img/churches/goshavank.jpg",
        ],
    },
    {
        "id": "marmashen",
        "name_hy": "Մարմաշեն վանք",
        "name_en": "Marmashen Monastery",
        "period": "old",
        "century": "X–XI դար",
        "year": 988,
        "location_hy": "Շիրակի մարզ, Մարմաշեն գյուղ",
        "location_en": "Shirak Province, Marmashen village",
        "address_hy": "Մարմաշեն, Շիրակի մարզ",
        "address_en": "Marmashen, Shirak Province",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=40.8523,43.7841",
        "image_main": "/static/img/churches/Marmashen.jpg",
        "image_old": "/static/img/churches/Marmashen1.jpg",
        "image_new": "/static/img/churches/Marmashen.jpg",
        "images": [
            "/static/img/churches/Marmashen.jpg",
            "/static/img/churches/Marmashen1.jpg",
            "/static/img/churches/Marmashen2.jpg",
        ],
    },
    {
        "id": "shoghakat",
        "name_hy": "Շողակաթ եկեղեցի",
        "name_en": "Shoghakat Church",
        "period": "old",
        "century": "XVII դար",
        "year": 1694,
        "location_hy": "Վաղարշապատ (Էջմիածին), Արմավիրի մարզ",
        "location_en": "Vagharshapat (Etchmiadzin), Armavir Province",
        "address_hy": "Վաղարշապատ, Արմավիրի մարզ",
        "address_en": "Vagharshapat, Armavir Province",
        "unesco": True,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=40.1567,44.2889",
        "image_main": "/static/img/churches/shoghakat.jpg",
        "image_old": "/static/img/churches/shoghakat-old.jpg",
        "image_new": "/static/img/churches/shoghakat-new.jpg",
        "images": [
            "/static/img/churches/shoghakat-old.jpg",
            "/static/img/churches/shoghakat-new.jpg",
            "/static/img/churches/shoghakat.jpg",
        ],
    },
    {
        "id": "aruchavank",
        "name_hy": "Արուճի Սուրբ Գրիգոր եկեղեցի",
        "name_en": "Aruch Saint Gregory Church",
        "period": "old",
        "century": "VII դար",
        "year": 666,
        "location_hy": "Արագածոտնի մարզ, Արուճ գյուղ",
        "location_en": "Aragatsotn Province, Aruch village",
        "address_hy": "Արուճ 0210, Արագածոտնի մարզ",
        "address_en": "Aruch 0210, Aragatsotn Province",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=40.2856,44.0231",
        "image_main": "/static/img/churches/aruchavank-old.jpg",
        "image_old": "/static/img/churches/aruchavank-old.jpg",
        "image_new": "/static/img/churches/aruchavank-inside.webp",
        "images": [
            "/static/img/churches/aruchavank-old.jpg",
            "/static/img/churches/aruchavank-inside.webp",
        ],
    },
    {
        "id": "saghmosavank",
        "name_hy": "Սաղմոսավանք",
        "name_en": "Saghmosavank Monastery",
        "period": "old",
        "century": "XIII դար",
        "year": 1215,
        "location_hy": "Արագածոտնի մարզ, Սաղմոսավան",
        "location_en": "Aragatsotn Province, Saghmosavan",
        "address_hy": "Սաղմոսավան 0211, Արագածոտնի մարզ",
        "address_en": "Saghmosavan 0211, Aragatsotn Province",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=40.3803,44.3956",
        "image_main": "/static/img/churches/saghmosavank-new.jpg",
        "image_old": "/static/img/churches/saghmosavank-old.jpg",
        "image_new": "/static/img/churches/saghmosavank-new.jpg",
        "images": [
            "/static/img/churches/saghmosavank-old.jpg",
            "/static/img/churches/saghmosavank-new.jpg",
        ],
    },
    {
        "id": "hovhannavank",
        "name_hy": "Հովհաննավանք",
        "name_en": "Hovhannavank Monastery",
        "period": "old",
        "century": "IV–XIII դար",
        "year": 1216,
        "location_hy": "Արագածոտնի մարզ, Օհանավան",
        "location_en": "Aragatsotn Province, Ohanavan",
        "address_hy": "Օհանավան 0225, Արագածոտնի մարզ",
        "address_en": "Ohanavan 0225, Aragatsotn Province",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=40.3396,44.3888",
        "image_main": "/static/img/churches/hovanavank_hervic.jpg",
        "image_old": "/static/img/churches/hovanavanq_old.jpg",
        "image_new": "/static/img/churches/hovanavank_hervic.jpg",
        "images": [
            "/static/img/churches/hovanavanq_old.jpg",
            "/static/img/churches/hovanavank_hervic.jpg",
            "/static/img/churches/hovhanavanq.avif",
        ],
    },
    {
        "id": "odzun-horomayr",
        "name_hy": "Օձունի և Հորոմայրի վանքեր",
        "name_en": "Odzun and Horomayr Monasteries",
        "period": "old",
        "century": "V–XII դար",
        "year": 1100,
        "location_hy": "Լոռու մարզ, Օձուն գյուղ",
        "location_en": "Lori Province, Odzun village",
        "address_hy": "Օձուն 1731, Լոռու մարզ",
        "address_en": "Odzun 1731, Lori Province",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=41.0506,44.6158",
        "image_main": "/static/img/churches/Odzun-new.jpg",
        "image_old": "/static/img/churches/odzun_old.jpg",
        "image_new": "/static/img/churches/Odzun-new.jpg",
        "images": [
            "/static/img/churches/odzun_old.jpg",
            "/static/img/churches/Odzun-new.jpg",
            "/static/img/churches/horomayr_dzor.jpg",
        ],
    },
    {
        "id": "gndevank",
        "name_hy": "Գնդեվանք",
        "name_en": "Gndevank Monastery",
        "period": "old",
        "century": "X դար",
        "year": 936,
        "location_hy": "Վայոց ձոր, Գնդեվազ գյուղ",
        "location_en": "Vayots Dzor, Gndevaz village",
        "address_hy": "Գնդեվազ 3704, Վայոց ձոր",
        "address_en": "Gndevaz 3704, Vayots Dzor",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=39.7588,45.6111",
        "image_main": "/static/img/churches/Gndevank.jpg",
        "image_old": "/static/img/churches/Gndevank1.jpg",
        "image_new": "/static/img/churches/Gndevank.jpg",
        "images": [
            "/static/img/churches/Gndevank1.jpg",
            "/static/img/churches/Gndevank.jpg",
            "/static/img/churches/Gndevank2.jpg",
        ],
    },
    # ══════════════════════════════
    # ՆՈՐ (ԺԱՄԱՆԱԿԱԿԻՑ) ԵԿԵՂԵՑԻՆԵՐ
    # ══════════════════════════════
    {
        "id": "saint-gregory-yerevan",
        "name_hy": "Սուրբ Գրիգոր Լուսավորիչ մայր տաճար",
        "name_en": "Saint Gregory the Illuminator Cathedral",
        "period": "new",
        "century": "XXI դար",
        "year": 2001,
        "location_hy": "Երևան, Կենտրոն",
        "location_en": "Yerevan, Kentron District",
        "address_hy": "Երվանդ Քոչարի փողոց, Երևան",
        "address_en": "Yervand Kochar Street, Yerevan",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=40.1719,44.5169",
        "image_main": "/static/img/churches/Saint-Gregory_1.jpg",
        "image_old": "/static/img/churches/Saint-Gregory_1.jpg",
        "image_new": "/static/img/churches/Saint_Gregory_2.webp",
        "images": [
            "/static/img/churches/Saint-Gregory_1.jpg",
            "/static/img/churches/Saint_Gregory_2.webp",
        ],
    },
    {
        "id": "saint-anna-yerevan",
        "name_hy": "Սուրբ Աննա եկեղեցի",
        "name_en": "Saint Anna Church",
        "period": "new",
        "century": "XXI դար",
        "year": 2015,
        "location_hy": "Երևան, Աբովյան փողոց",
        "location_en": "Yerevan, Abovyan Street",
        "address_hy": "Աբովյան և Սայաթ-Նովա փողոցների խաչմերուկ",
        "address_en": "Abovyan and Sayat-Nova intersection",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=40.1844,44.5191",
        "image_main": "/static/img/churches/saint-anna-1.jpg",
        "image_old": "/static/img/churches/saint-anna-1.jpg",
        "image_new": "/static/img/churches/saint-anna-2.jpg",
        "images": [
            "/static/img/churches/saint-anna-1.jpg",
            "/static/img/churches/saint-anna-2.jpg",
        ],
    },
    {
        "id": "saint-thaddeus-masis",
        "name_hy": "Սուրբ Թադևոս եկեղեցի",
        "name_en": "Saint Thaddeus Church",
        "period": "new",
        "century": "XXI դար",
        "year": 2015,
        "location_hy": "Մասիս, Արարատի մարզ",
        "location_en": "Masis, Ararat Province",
        "address_hy": "Մասիս, Արարատի մարզ",
        "address_en": "Masis, Ararat Province",
        "unesco": False,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=39.9995,44.4372",
        "image_main": "/static/img/churches/SaintTadeosGlxavor.jpg",
        "image_old": "/static/img/churches/SaintTadeos11.jpg",
        "image_new": "/static/img/churches/SaintTadeosGlxavor.jpg",
        "images": [
            "/static/img/churches/SaintTadeos11.jpg",
            "/static/img/churches/SaintTadeos.jpg",
            "/static/img/churches/SaintTadeosGlxavor.jpg",
        ],
    },
]

